version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    image: ivanmakovetskiy/devops-for-programmers-project-74:latest
    command: bash -c 'sleep 3 && npm test'
    depends_on:
      - db
    environment:
      DATABASE_NAME: postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_PORT: 5432
      DATABASE_HOST: ${DATABASE_HOST}

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
     - 5432:5432
